<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f8d43373-4cef-49fa-a77b-de9d6b056fbd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\css\NewFolder\**" />
    <Compile Remove="wwwroot\NewFolder1\**" />
    <Compile Remove="wwwroot\NewFolder\**" />
    <Content Remove="wwwroot\css\NewFolder\**" />
    <Content Remove="wwwroot\NewFolder1\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="wwwroot\css\NewFolder\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder1\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <None Remove="wwwroot\css\NewFolder\**" />
    <None Remove="wwwroot\NewFolder1\**" />
    <None Remove="wwwroot\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\NewFolder2\" />
  </ItemGroup>

</Project>
